"""remove index from name field of Admin

Revision ID: 12394339d21a
Revises: 38f510db05cc
Create Date: 2021-10-23 09:37:51.323073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12394339d21a'
down_revision = '38f510db05cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admin_name', table_name='admin')
    op.create_unique_constraint(None, 'admin', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin', type_='unique')
    op.create_index('ix_admin_name', 'admin', ['name'], unique=False)
    # ### end Alembic commands ###
