"""update numbers to non unique okay

Revision ID: 2dc2259cc497
Revises: 0ae15b97e4ba
Create Date: 2021-10-17 18:51:39.776817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dc2259cc497'
down_revision = '0ae15b97e4ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('number_digits_key', 'number', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('number_digits_key', 'number', ['digits'])
    # ### end Alembic commands ###
